
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004550
     time (cpu & wall) for ordering          =        0.343750        0.413030
     time (cpu & wall) for other matrix prep =        0.062500        0.061592
     time (cpu & wall) for value input       =        0.000000        0.010689
     time (cpu & wall) for matrix distrib.   =        0.046875        0.070649
     time (cpu & wall) for numeric factor    =        0.250000        0.386452
     computational rate (gflops) for factor  =       47.023927       30.420305
     time (cpu & wall) for numeric solve     =        0.015625        0.024067
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012174
     time (cpu & wall) for matrix distrib.   =        0.046875        0.067938
     time (cpu & wall) for numeric factor    =        0.265625        0.352090
     computational rate (gflops) for factor  =       44.257813       33.389138

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011865
     time (cpu & wall) for matrix distrib.   =        0.000000        0.059517
     time (cpu & wall) for numeric factor    =        0.203125        0.308214
     computational rate (gflops) for factor  =       57.875602       38.142221
     time (cpu & wall) for numeric solve     =        0.015625        0.019355
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010829
     time (cpu & wall) for matrix distrib.   =        0.046875        0.066098
     time (cpu & wall) for numeric factor    =        0.281250        0.316795
     computational rate (gflops) for factor  =       41.799046       37.109090
     time (cpu & wall) for numeric solve     =        0.015625        0.019171
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012220
     time (cpu & wall) for matrix distrib.   =        0.062500        0.066245
     time (cpu & wall) for numeric factor    =        0.296875        0.344520
     computational rate (gflops) for factor  =       39.599096       34.122784

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012061
     time (cpu & wall) for matrix distrib.   =        0.062500        0.065015
     time (cpu & wall) for numeric factor    =        0.234375        0.296439
     computational rate (gflops) for factor  =       50.158855       39.657365

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010480
     time (cpu & wall) for matrix distrib.   =        0.046875        0.066636
     time (cpu & wall) for numeric factor    =        0.234375        0.306399
     computational rate (gflops) for factor  =       50.158855       38.368212
     time (cpu & wall) for numeric solve     =        0.015625        0.019838
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012224
     time (cpu & wall) for matrix distrib.   =        0.046875        0.063084
     time (cpu & wall) for numeric factor    =        0.328125        0.334994
     computational rate (gflops) for factor  =       35.827754       35.093153
     time (cpu & wall) for numeric solve     =        0.015625        0.019897
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008527
     time (cpu & wall) for matrix distrib.   =        0.046875        0.055938
     time (cpu & wall) for numeric factor    =        0.296875        0.316549
     computational rate (gflops) for factor  =       39.599096       37.137999

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011950
     time (cpu & wall) for matrix distrib.   =        0.046875        0.058779
     time (cpu & wall) for numeric factor    =        0.234375        0.309130
     computational rate (gflops) for factor  =       50.158855       38.029286
     time (cpu & wall) for numeric solve     =        0.031250        0.018597
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008681
     time (cpu & wall) for matrix distrib.   =        0.078125        0.065475
     time (cpu & wall) for numeric factor    =        0.296875        0.337385
     computational rate (gflops) for factor  =       39.599096       34.844370

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.008734
     time (cpu & wall) for matrix distrib.   =        0.046875        0.054241
     time (cpu & wall) for numeric factor    =        0.250000        0.304634
     computational rate (gflops) for factor  =       47.023927       38.590485

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.008962
     time (cpu & wall) for matrix distrib.   =        0.046875        0.059588
     time (cpu & wall) for numeric factor    =        0.203125        0.291422
     computational rate (gflops) for factor  =       57.875602       40.340062
     time (cpu & wall) for numeric solve     =        0.015625        0.020074
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010390
     time (cpu & wall) for matrix distrib.   =        0.062500        0.061340
     time (cpu & wall) for numeric factor    =        0.250000        0.346737
     computational rate (gflops) for factor  =       47.023927       33.904597

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011915
     time (cpu & wall) for matrix distrib.   =        0.062500        0.060268
     time (cpu & wall) for numeric factor    =        0.265625        0.309019
     computational rate (gflops) for factor  =       44.257813       38.042970

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012062
     time (cpu & wall) for matrix distrib.   =        0.046875        0.065084
     time (cpu & wall) for numeric factor    =        0.234375        0.329675
     computational rate (gflops) for factor  =       50.158855       35.659295
     time (cpu & wall) for numeric solve     =        0.015625        0.019406
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008693
     time (cpu & wall) for matrix distrib.   =        0.046875        0.059963
     time (cpu & wall) for numeric factor    =        0.250000        0.342719
     computational rate (gflops) for factor  =       47.023927       34.302101
     time (cpu & wall) for numeric solve     =        0.015625        0.019396
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.009058
     time (cpu & wall) for matrix distrib.   =        0.015625        0.058025
     time (cpu & wall) for numeric factor    =        0.234375        0.289446
     computational rate (gflops) for factor  =       50.158855       40.615415
     time (cpu & wall) for numeric solve     =        0.015625        0.020156
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008693
     time (cpu & wall) for matrix distrib.   =        0.031250        0.066588
     time (cpu & wall) for numeric factor    =        0.296875        0.341694
     computational rate (gflops) for factor  =       39.599096       34.404979
     time (cpu & wall) for numeric solve     =        0.015625        0.019170
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011578
     time (cpu & wall) for matrix distrib.   =        0.015625        0.063640
     time (cpu & wall) for numeric factor    =        0.296875        0.333765
     computational rate (gflops) for factor  =       39.599096       35.222385

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008702
     time (cpu & wall) for matrix distrib.   =        0.031250        0.063438
     time (cpu & wall) for numeric factor    =        0.296875        0.340692
     computational rate (gflops) for factor  =       39.599096       34.506237

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011995
     time (cpu & wall) for matrix distrib.   =        0.031250        0.062795
     time (cpu & wall) for numeric factor    =        0.218750        0.343585
     computational rate (gflops) for factor  =       53.741630       34.215663

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011970
     time (cpu & wall) for matrix distrib.   =        0.046875        0.064298
     time (cpu & wall) for numeric factor    =        0.296875        0.338187
     computational rate (gflops) for factor  =       39.599096       34.761738
     time (cpu & wall) for numeric solve     =        0.015625        0.019681
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008656
     time (cpu & wall) for matrix distrib.   =        0.031250        0.062861
     time (cpu & wall) for numeric factor    =        0.250000        0.335928
     computational rate (gflops) for factor  =       47.023927       34.995529

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.011934
     time (cpu & wall) for matrix distrib.   =        0.031250        0.065258
     time (cpu & wall) for numeric factor    =        0.296875        0.341358
     computational rate (gflops) for factor  =       39.599096       34.438874
     time (cpu & wall) for numeric solve     =        0.015625        0.019684
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.012180
     time (cpu & wall) for matrix distrib.   =        0.015625        0.068978
     time (cpu & wall) for numeric factor    =        0.218750        0.308411
     computational rate (gflops) for factor  =       53.741630       38.117906

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012164
     time (cpu & wall) for matrix distrib.   =        0.031250        0.062789
     time (cpu & wall) for numeric factor    =        0.281250        0.310674
     computational rate (gflops) for factor  =       41.799046       37.840310

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008552
     time (cpu & wall) for matrix distrib.   =        0.031250        0.057911
     time (cpu & wall) for numeric factor    =        0.218750        0.318639
     computational rate (gflops) for factor  =       53.741630       36.894371

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010400
     time (cpu & wall) for matrix distrib.   =        0.000000        0.059630
     time (cpu & wall) for numeric factor    =        0.265625        0.317289
     computational rate (gflops) for factor  =       44.257813       37.051372
     time (cpu & wall) for numeric solve     =        0.015625        0.019346
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012168
     time (cpu & wall) for matrix distrib.   =        0.062500        0.063909
     time (cpu & wall) for numeric factor    =        0.281250        0.347294
     computational rate (gflops) for factor  =       41.799046       33.850210
     time (cpu & wall) for numeric solve     =        0.031250        0.021433
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010952
     time (cpu & wall) for matrix distrib.   =        0.031250        0.064481
     time (cpu & wall) for numeric factor    =        0.218750        0.298747
     computational rate (gflops) for factor  =       53.741630       39.350909

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012130
     time (cpu & wall) for matrix distrib.   =        0.062500        0.068341
     time (cpu & wall) for numeric factor    =        0.234375        0.344379
     computational rate (gflops) for factor  =       50.158855       34.136775

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008709
     time (cpu & wall) for matrix distrib.   =        0.031250        0.061713
     time (cpu & wall) for numeric factor    =        0.312500        0.297798
     computational rate (gflops) for factor  =       37.619141       39.476362

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008517
     time (cpu & wall) for matrix distrib.   =        0.062500        0.066932
     time (cpu & wall) for numeric factor    =        0.234375        0.305506
     computational rate (gflops) for factor  =       50.158855       38.480363

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008912
     time (cpu & wall) for matrix distrib.   =        0.046875        0.063660
     time (cpu & wall) for numeric factor    =        0.234375        0.340391
     computational rate (gflops) for factor  =       50.158855       34.536659
     time (cpu & wall) for numeric solve     =        0.015625        0.019502
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012079
     time (cpu & wall) for matrix distrib.   =        0.015625        0.064233
     time (cpu & wall) for numeric factor    =        0.203125        0.349638
     computational rate (gflops) for factor  =       57.875602       33.623266

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008520
     time (cpu & wall) for matrix distrib.   =        0.078125        0.056940
     time (cpu & wall) for numeric factor    =        0.234375        0.322726
     computational rate (gflops) for factor  =       50.158855       36.427152
     time (cpu & wall) for numeric solve     =        0.015625        0.019549
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008483
     time (cpu & wall) for matrix distrib.   =        0.062500        0.059241
     time (cpu & wall) for numeric factor    =        0.312500        0.338107
     computational rate (gflops) for factor  =       37.619141       34.770014
     time (cpu & wall) for numeric solve     =        0.015625        0.019354
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.009763
     time (cpu & wall) for matrix distrib.   =        0.046875        0.063581
     time (cpu & wall) for numeric factor    =        0.234375        0.298552
     computational rate (gflops) for factor  =       50.158855       39.376729

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008451
     time (cpu & wall) for matrix distrib.   =        0.046875        0.059398
     time (cpu & wall) for numeric factor    =        0.265625        0.343860
     computational rate (gflops) for factor  =       44.257813       34.188319

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011761
     time (cpu & wall) for matrix distrib.   =        0.062500        0.065013
     time (cpu & wall) for numeric factor    =        0.281250        0.303209
     computational rate (gflops) for factor  =       41.799046       38.771914

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010752
     time (cpu & wall) for matrix distrib.   =        0.015625        0.062378
     time (cpu & wall) for numeric factor    =        0.265625        0.351113
     computational rate (gflops) for factor  =       44.257813       33.482056

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           69581
     no. of nonzeroes in lower triangle of a =         1749701
     no. of nonzeroes in the factor l        =        20932939
     ratio of nonzeroes in factor (min/max)  =          0.9308
     number of super nodes                   =            2380
     maximum order of a front matrix         =            1682
     maximum size of a front matrix          =         1415403
     maximum size of a front trapezoid       =          681030
     no. of floating point ops for factor    =      1.1756D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8353
     ratio of allocated memory (max/min)     =          1.1895
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.011699
     time (cpu & wall) for matrix distrib.   =        0.046875        0.061783
     time (cpu & wall) for numeric factor    =        0.218750        0.325404
     computational rate (gflops) for factor  =       53.741630       36.127298
     time (cpu & wall) for numeric solve     =        0.015625        0.019255
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        253177.        2. MB
                95-   1        262144.        2. MB        231852.        2. MB
                95-   2        262144.        2. MB        238955.        2. MB
                95-   3        262144.        2. MB        257633.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        981617.        7. MB


  Solver Memory allocated on core    0       =       81.925 MB
  Solver Memory allocated on core    1       =       68.875 MB
  Solver Memory allocated on core    2       =       73.511 MB
  Solver Memory allocated on core    3       =       74.177 MB
  Total Solver Memory allocated by all cores =      298.488 MB

